#!/usr/bin/env python3
"""
Master script to generate all LaTeX tables at once.
Outputs can be redirected to a file or used directly.
"""

import subprocess
import sys
import os

SCRIPTS = [
    ("ucf101_main_results.py", "Main UCF101 Results"),
    ("ucf101_videomix_results.py", "UCF101 VideoMix Results"),
    ("1_temporal_view.py", "UCF101 1 Temporal View"),
    ("ucf101_combined_augmentation.py", "UCF101 Combined Augmentations"),
    ("train_augmented.py", "UCF101 Train with Augmentations"),
    ("individual_augmentation.py", "UCF101 Individual Augmentations"),
    ("removed_black_strip.py", "UCF101 Removed Black Strips"),
    ("distribution_tables.py", "Class Distribution Analysis"),
    ("kinetics400_zero_shot.py", "Kinetics400 Zero-shot"),
    ("kinetics400_kshot.py", "Kinetics400 K-shot"),
    ("hmdb51_zero_shot.py", "HMDB51 Zero-shot"),
    ("hmdb51_kshot.py", "HMDB51 K-shot"),
]

def generate_all_tables():
    """Generate all tables and print them with section headers."""
    tables_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(tables_dir))
    
    for script, description in SCRIPTS:
        print()
        print("%" + "=" * 78)
        print(f"% {description}")
        print("%" + "=" * 78)
        print()
        
        script_path = os.path.join(tables_dir, script)
        try:
            # Set PYTHONPATH to project root for imports to work
            env = os.environ.copy()
            env['PYTHONPATH'] = project_root
            
            result = subprocess.run(
                [sys.executable, script_path],
                capture_output=True,
                text=True,
                check=True,
                env=env,
                cwd=project_root
            )
            print(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"% ERROR running {script}: {e}", file=sys.stderr)
            print(f"% {e.stderr}", file=sys.stderr)
        except FileNotFoundError:
            print(f"% ERROR: Script not found: {script}", file=sys.stderr)

if __name__ == "__main__":
    print("% LaTeX Tables Generated by Master Script")
    print("% Run from: notebooks/tables/generate_all_tables.py")
    print()
    generate_all_tables()
